version: '3.2'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express:latest
    ports:
      - 8081:8081
volumes:
  db_data: